# Generated by Django 4.1.7 on 2023-04-09 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Opiniones',
            old_name='nombre',
            new_name='articulo',
        ),
    ]
